parameters:
#    symfony_tn_demo.example.class: SymfonyTn\DemoBundle\Example

services:
#    symfony_tn_demo.example:
#        class: %symfony_tn_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
