admin_news:
    pattern:  /
    defaults: { _controller: "SymfonyTnDemoBundle:News:index" }

admin_news_show:
    pattern:  /{id}/show
    defaults: { _controller: "SymfonyTnDemoBundle:News:show" }

admin_news_new:
    pattern:  /new
    defaults: { _controller: "SymfonyTnDemoBundle:News:new" }

admin_news_create:
    pattern:  /create
    defaults: { _controller: "SymfonyTnDemoBundle:News:create" }
    requirements: { _method: post }

admin_news_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SymfonyTnDemoBundle:News:edit" }

admin_news_update:
    pattern:  /{id}/update
    defaults: { _controller: "SymfonyTnDemoBundle:News:update" }
    requirements: { _method: post|put }

admin_news_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SymfonyTnDemoBundle:News:delete" }
    requirements: { _method: post|delete }
